### ISSUE TITLE
Incorrect offset for reading 1 byte file

### ISSUE THREAD

**Issue by c3-robin** [cloudonix/vertx-java.io#4]
A bug on this line [vertx-java.io/src/main/java/io/cloudonix/vertx/javaio/WriteToInputStream.java at a5de4c13e6d121814260482ef98bc213f62e3ec2 · cloudonix/vertx-java.io](https://github.com/cloudonix/vertx-java.io/blob/a5de4c13e6d121814260482ef98bc213f62e3ec2/src/main/java/io/cloudonix/vertx/javaio/WriteToInputStream.java#L206)
Basically, when read(b, off + 1, len - 1) reaches end of stream, it returns -1. Here 1 + (-1) would be 0, but we actually want offset to be 1 because the byte from read() could be successful. It’s the offset for the buffer set improperly. This caused the 1 byte to be lost

This failure only happens when:
1. the file has only one byte
2. the read from the buffer in WriteToInpusStream happens before the write of the first byte.

**Comment by guss77** [comment]
Fixed in 1.4.0
